-- sketch_routes_judge_llm.sql — INTEGRATION SHAPE ONLY (not loaded by app.sql).
-- Promote only if product accepts non-deterministic optional 4th judge chips
-- on flagged residuals. See docs/llm-judge.md.
--
-- When to run: NEVER at boot. NEVER on high-band bulk-accept candidates.
-- Only on residual human queue: v_suggestions_judged WHERE judge_band='flagged'
-- (or panel_signal IN ('split','conflict')) — async after seed judges land.
--
-- Queue shape (quackapi):
--   CREATE QUEUE llm_judge_jobs;
--   Worker / cron SQL: dequeue → http_post Ollama → COPY vote JSON to
--   exports/llm_votes/<suggestion_id>_<judge_key>.json → ack.
--   UI reads votes via read_json glob (same pattern as decisions/).

-- ── hypothetical tables (CTAS from residual queue) ──────────────────────────
-- CREATE OR REPLACE TABLE llm_judge_queue AS
-- SELECT s.id AS suggestion_id, s.text, s.context, e.kind, s.confidence,
--        p.panel_signal, p.confidence AS panel_confidence
-- FROM v_suggestions s
-- JOIN v_judge_panel p ON p.suggestion_id = s.id
-- LEFT JOIN entities e ON e.id = s.entity_id
-- WHERE s.band = 'flagged' OR p.panel_signal IN ('split', 'conflict');

-- ── preferred call path: http_client (model varies per row) ────────────────
-- INSTALL http_client FROM community; LOAD http_client;
--
-- CREATE OR REPLACE MACRO llm_judge_prompt(text, kind, context) AS
--   concat(
--     'FOIA redaction judge. JSON only {"verdict":"redact"|"keep","score":0-100,"reason":"one line"}. ',
--     'redact=subject/witness PII; keep=citation, street-only, officer. ',
--     'text="', coalesce(text, ''), '" kind=', coalesce(kind, '?'),
--     ' ctx="', coalesce(context, ''), '".'
--   );
--
-- -- One model at a time (load cost); two judges = two queued job types.
-- CREATE OR REPLACE TABLE llm_votes_batch AS
-- WITH posted AS (
--   SELECT
--     q.suggestion_id,
--     'qwen25_brief' AS judge_key,
--     'qwen2.5:7b' AS model,
--     http_post(
--       'http://127.0.0.1:11434/api/generate',
--       map {'Content-Type': 'application/json'},
--       {
--         'model': 'qwen2.5:7b',
--         'prompt': llm_judge_prompt(q.text, q.kind, q.context),
--         'stream': false,
--         'format': 'json',
--         'options': {'temperature': 0, 'num_predict': 100}
--       }::JSON
--     ) AS resp
--   FROM llm_judge_queue q
--   LIMIT 32   -- batch size; never full corpus in one request
-- )
-- SELECT
--   suggestion_id,
--   judge_key,
--   model,
--   (resp ->> 'body')::JSON ->> 'response' AS raw_json,
--   try_cast(((resp ->> 'body')::JSON ->> 'total_duration') AS BIGINT) / 1000000 AS latency_ms
-- FROM posted;

-- ── optional route (on-demand single suggestion — demos only) ──────────────
-- CREATE OR REPLACE ROUTE api_suggestion_llm_judges
-- GET '/api/suggestions/:id/llm-judges' AS
-- SELECT
--   suggestion_id,
--   judge_key,
--   model,
--   verdict,
--   score,
--   reason,
--   latency_ms,
--   judged_at
-- FROM v_llm_votes
-- WHERE suggestion_id = CAST($id AS INTEGER)
-- ORDER BY judge_key;
--
-- -- Persist: COPY each vote to exports/llm_votes/*.json (append-only, audit).
-- -- Do NOT UPDATE suggestions.confidence — LLM is a projection chip, same as
-- -- the deterministic panel (seed confidence stays reproducible).

-- ── queue lifecycle (if quackapi CREATE QUEUE is available) ─────────────────
-- CREATE QUEUE llm_judge_jobs;
--
-- -- Enqueue after boot (or on demand from UI "Ask LLM judges"):
-- -- SELECT quackapi_enqueue('llm_judge_jobs',
-- --   json_object('suggestion_id', suggestion_id, 'model', 'qwen2.5:7b'))
-- -- FROM llm_judge_queue;
--
-- -- Worker (separate duckdb process OR cronjob extension tick):
-- --   job := quackapi_dequeue('llm_judge_jobs');
-- --   run http_post judge; COPY result JSON; quackapi_ack(...);
--
-- Polling UI: GET /api/suggestions/:id/llm-judges returns [] until files appear.

-- ── hard product rules if promoted ─────────────────────────────────────────
-- 1. Never block export or bulk-accept on LLM completion.
-- 2. Never send PII to hosted APIs (Ollama localhost only; allowlist hosts).
-- 3. Show as optional chip "LLM (local)" — not a 4th equal vote in panel_signal.
-- 4. Require model+prompt version string on every stored vote for audit.
-- 5. Prefer ≥7B class models; 3B over-applies street/surname heuristics (measured).
