#!/usr/bin/env bash
# install-runtime.sh — one-shot quackapi runtime for Closure (no source vendoring).
#
# Graders never need to know about quackapi. This script puts a working
# DuckDB binary + quackapi extension under .deps/runtime/ so run.sh just works.
#
# Resolution order (first hit wins):
#   1. Explicit env: DUCKDB_BIN + QUACKAPI_EXT (already valid paths)
#   2. Cached .deps/runtime from a previous install
#   3. Sibling checkout ../quackapi/build/release (dev machines)
#   4. Download prebuilt tarball from GitHub Releases (CLOSURE_RUNTIME_TAG)
#   5. Clone + build quackapi from source into .deps/src/quackapi (slow fallback)
#
# Usage (from repo root or anywhere):
#   ./scripts/install-runtime.sh
#   ./scripts/install-runtime.sh --force          # re-download / rebuild
#   CLOSURE_RUNTIME_TAG=runtime-v1.5.4-1 ./scripts/install-runtime.sh
#
# Does NOT vendor quackapi source into the Closure tree. .deps/ is gitignored.
set -euo pipefail

ROOT="$(cd "$(dirname "$0")/.." && pwd)"
cd "$ROOT"

DEPS_DIR="${CLOSURE_DEPS_DIR:-$ROOT/.deps}"
RUNTIME_DIR="$DEPS_DIR/runtime"
MARKER="$RUNTIME_DIR/.installed"
# Pin so a random floating "latest" cannot surprise graders mid-review.
RUNTIME_TAG="${CLOSURE_RUNTIME_TAG:-runtime-v1.5.4-1}"
RUNTIME_REPO="${CLOSURE_RUNTIME_REPO:-asubbarao/closure}"
QUACKAPI_GIT="${CLOSURE_QUACKAPI_GIT:-https://github.com/asubbarao/quackapi.git}"
FORCE=0

while [[ $# -gt 0 ]]; do
  case "$1" in
    --force|-f) FORCE=1; shift ;;
    --tag) RUNTIME_TAG="$2"; shift 2 ;;
    -h|--help)
      sed -n '2,28p' "$0"
      exit 0
      ;;
    *)
      echo "error: unknown arg: $1" >&2
      exit 1
      ;;
  esac
done

# ── platform triple used in release asset names ─────────────────────────────
detect_platform() {
  local os arch
  os="$(uname -s | tr '[:upper:]' '[:lower:]')"
  arch="$(uname -m)"
  case "$os" in
    darwin)
      case "$arch" in
        arm64|aarch64) echo "osx_arm64" ;;
        x86_64|amd64)  echo "osx_amd64" ;;
        *) echo "error: unsupported mac arch: $arch" >&2; return 1 ;;
      esac
      ;;
    linux)
      case "$arch" in
        x86_64|amd64)  echo "linux_amd64" ;;
        aarch64|arm64) echo "linux_arm64" ;;
        *) echo "error: unsupported linux arch: $arch" >&2; return 1 ;;
      esac
      ;;
    *)
      echo "error: unsupported OS: $os (need macOS or Linux)" >&2
      return 1
      ;;
  esac
}

have_pair() {
  local bin="$1" ext="$2"
  [[ -n "$bin" && -x "$bin" && -n "$ext" && -f "$ext" ]]
}

write_env() {
  local bin="$1" ext="$2"
  mkdir -p "$RUNTIME_DIR"
  # Prefer stable paths inside .deps when we control the install layout.
  cat > "$RUNTIME_DIR/env" <<EOF
# Generated by scripts/install-runtime.sh — sourced by run.sh / setup.
export DUCKDB_BIN='$bin'
export QUACKAPI_EXT='$ext'
export CLOSURE_QUACKAPI_EXT='$ext'
EOF
  {
    echo "installed_at=$(date -u +%Y-%m-%dT%H:%M:%SZ)"
    echo "platform=$(detect_platform 2>/dev/null || echo unknown)"
    echo "tag=$RUNTIME_TAG"
    echo "duckdb_bin=$bin"
    echo "quackapi_ext=$ext"
  } > "$MARKER"
  echo "==> runtime ready"
  echo "    DUCKDB_BIN=$bin"
  echo "    QUACKAPI_EXT=$ext"
}

copy_pair_into_deps() {
  local bin="$1" ext="$2"
  mkdir -p "$RUNTIME_DIR"
  # Copy (not symlink) so the sibling tree can be deleted without breaking Closure.
  /bin/cp -f "$bin" "$RUNTIME_DIR/duckdb"
  /bin/cp -f "$ext" "$RUNTIME_DIR/quackapi.duckdb_extension"
  chmod +x "$RUNTIME_DIR/duckdb"
  write_env "$RUNTIME_DIR/duckdb" "$RUNTIME_DIR/quackapi.duckdb_extension"
}

probe_pair() {
  local bin="$1" ext="$2"
  # Cheap smoke: LOAD + CREATE ROUTE must parse (the whole point of quackapi).
  "$bin" -unsigned -cmd "LOAD '${ext}';" -c \
    "CREATE OR REPLACE ROUTE _closure_rt_probe GET '/_closure_rt_probe' AS SELECT 1 AS ok; DROP ROUTE _closure_rt_probe;" \
    >/dev/null 2>&1
}

echo "==> Closure runtime install (repo: $ROOT)"
echo "    tag=$RUNTIME_TAG  deps=$DEPS_DIR"

# 1) Explicit env (developer override)
if [[ $FORCE -eq 0 ]] && have_pair "${DUCKDB_BIN:-}" "${QUACKAPI_EXT:-${CLOSURE_QUACKAPI_EXT:-}}"; then
  EXT="${QUACKAPI_EXT:-$CLOSURE_QUACKAPI_EXT}"
  if probe_pair "$DUCKDB_BIN" "$EXT"; then
    echo "==> using DUCKDB_BIN / QUACKAPI_EXT from environment"
    write_env "$DUCKDB_BIN" "$EXT"
    exit 0
  fi
  echo "warn: env paths present but CREATE ROUTE probe failed — continuing" >&2
fi

# 2) Cached .deps/runtime
if [[ $FORCE -eq 0 ]] && have_pair "$RUNTIME_DIR/duckdb" "$RUNTIME_DIR/quackapi.duckdb_extension"; then
  if probe_pair "$RUNTIME_DIR/duckdb" "$RUNTIME_DIR/quackapi.duckdb_extension"; then
    echo "==> using cached .deps/runtime"
    write_env "$RUNTIME_DIR/duckdb" "$RUNTIME_DIR/quackapi.duckdb_extension"
    exit 0
  fi
  echo "warn: cached runtime failed probe — reinstalling" >&2
fi

# 3) Sibling quackapi build (local dev). Skipped under --force so release
#    assets get exercised the same way a grader machine would.
SIBLING_ROOT="$(cd "$ROOT/.." && pwd)/quackapi"
SIBLING_BIN="$SIBLING_ROOT/build/release/duckdb"
SIBLING_EXT="$SIBLING_ROOT/build/release/extension/quackapi/quackapi.duckdb_extension"
if [[ $FORCE -eq 0 ]] && have_pair "$SIBLING_BIN" "$SIBLING_EXT"; then
  echo "==> found sibling quackapi build at $SIBLING_ROOT"
  copy_pair_into_deps "$SIBLING_BIN" "$SIBLING_EXT"
  exit 0
fi

# 4) Download prebuilt from Closure GitHub Releases
PLATFORM="$(detect_platform)"
# Asset names: closure-<tag>-<platform>.tar.gz
# e.g. tag=runtime-v1.5.4-1 → closure-runtime-v1.5.4-1-osx_arm64.tar.gz
ASSET="closure-${RUNTIME_TAG}-${PLATFORM}.tar.gz"
URL="https://github.com/${RUNTIME_REPO}/releases/download/${RUNTIME_TAG}/${ASSET}"
TMP_TGZ="$(mktemp -t closure-runtime.XXXXXX).tar.gz"
TMP_DIR="$(mktemp -d -t closure-runtime.XXXXXX)"
cleanup() { rm -rf "$TMP_DIR" "$TMP_TGZ" 2>/dev/null || true; }
trap cleanup EXIT

echo "==> trying prebuilt: $URL"
if /usr/bin/curl -fsSL --retry 3 --retry-delay 2 -o "$TMP_TGZ" "$URL"; then
  tar -xzf "$TMP_TGZ" -C "$TMP_DIR"
  # Accept either flat or nested layout inside the tarball.
  DL_BIN="$(find "$TMP_DIR" -type f -name duckdb | head -1)"
  DL_EXT="$(find "$TMP_DIR" -type f -name 'quackapi*.duckdb_extension' | head -1)"
  if have_pair "$DL_BIN" "$DL_EXT" && probe_pair "$DL_BIN" "$DL_EXT"; then
    echo "==> prebuilt runtime OK ($PLATFORM)"
    copy_pair_into_deps "$DL_BIN" "$DL_EXT"
    exit 0
  fi
  echo "warn: downloaded asset but probe failed — falling back to source build" >&2
else
  echo "warn: no prebuilt for $PLATFORM (HTTP miss) — falling back to source build" >&2
  echo "      (this is normal until a runtime release ships for your platform)" >&2
fi

# 5) Build from source into .deps/src (does not modify the Closure tree's product SQL)
echo "==> building quackapi from source (first time can take 10–30+ minutes)"
echo "    requires: git, cmake, ninja, a C++ toolchain"
for cmd in git cmake ninja; do
  if ! command -v "$cmd" >/dev/null 2>&1; then
    echo "error: missing '$cmd' — install it, or set DUCKDB_BIN + QUACKAPI_EXT to a prebuilt pair" >&2
    echo "  macOS:  brew install cmake ninja" >&2
    echo "  Ubuntu: sudo apt-get install -y cmake ninja-build build-essential git" >&2
    exit 1
  fi
done

SRC_DIR="$DEPS_DIR/src/quackapi"
mkdir -p "$DEPS_DIR/src"
if [[ ! -d "$SRC_DIR/.git" ]]; then
  echo "==> git clone --recurse-submodules $QUACKAPI_GIT"
  git clone --recurse-submodules --depth 1 "$QUACKAPI_GIT" "$SRC_DIR"
else
  echo "==> updating $SRC_DIR"
  git -C "$SRC_DIR" fetch --depth 1 origin
  git -C "$SRC_DIR" pull --ff-only || true
  git -C "$SRC_DIR" submodule update --init --recursive
fi

echo "==> GEN=ninja make release (in $SRC_DIR)"
(
  cd "$SRC_DIR"
  GEN=ninja make release
)

BUILD_BIN="$SRC_DIR/build/release/duckdb"
BUILD_EXT="$SRC_DIR/build/release/extension/quackapi/quackapi.duckdb_extension"
if ! have_pair "$BUILD_BIN" "$BUILD_EXT"; then
  echo "error: build finished but binary/extension missing under $SRC_DIR/build/release" >&2
  exit 1
fi
if ! probe_pair "$BUILD_BIN" "$BUILD_EXT"; then
  echo "error: built runtime failed CREATE ROUTE probe" >&2
  exit 1
fi

copy_pair_into_deps "$BUILD_BIN" "$BUILD_EXT"
echo "==> done. Next: make setup && make run"
